name: Commit Check

on:
  push:
    paths-ignore:
      - "docs/**"
      - "Changelog.md"
      - "README.md"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "Changelog.md"
      - "README.md"
  release:
    types: [published, created, edited]

jobs:
  build:
    name: check commit
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 60

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get -y install jq clang-format

      - name: Get PR title
        if: github.event_name == 'pull_request'
        id: get_pr_title
        run: echo "::set-output name=title::$(jq -r .title < $GITHUB_EVENT_PATH)"

      - name: Print PR title (for debugging)
        if: github.event_name == 'pullpull_request'
        run: echo "PR title is: ${{ steps.get_pr_title.outputs.title }}"

      - name: Check commit
        run: bash tools/.ci/check-commit.sh
        env:
          PR_TITLE: ${{ steps.get_pr_title.outputs.title }}

